name: Testes Automatizados

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Executar testes
      run: |
        pytest
